/**
 * Static US place, freight, and speech lexicons used by slot extraction.
 * Data only — never invent a ZIP or a rate from these tables.
 */

export const STATE_NAME_TO_CODE = {
  alabama: "AL",
  alaska: "AK",
  arizona: "AZ",
  arkansas: "AR",
  california: "CA",
  colorado: "CO",
  connecticut: "CT",
  delaware: "DE",
  florida: "FL",
  georgia: "GA",
  hawaii: "HI",
  idaho: "ID",
  illinois: "IL",
  indiana: "IN",
  iowa: "IA",
  kansas: "KS",
  kentucky: "KY",
  louisiana: "LA",
  maine: "ME",
  maryland: "MD",
  massachusetts: "MA",
  michigan: "MI",
  minnesota: "MN",
  mississippi: "MS",
  missouri: "MO",
  montana: "MT",
  nebraska: "NE",
  nevada: "NV",
  "new hampshire": "NH",
  "new jersey": "NJ",
  "new mexico": "NM",
  "new york": "NY",
  "north carolina": "NC",
  "north dakota": "ND",
  ohio: "OH",
  oklahoma: "OK",
  oregon: "OR",
  pennsylvania: "PA",
  "rhode island": "RI",
  "south carolina": "SC",
  "south dakota": "SD",
  tennessee: "TN",
  texas: "TX",
  utah: "UT",
  vermont: "VT",
  virginia: "VA",
  washington: "WA",
  "west virginia": "WV",
  wisconsin: "WI",
  wyoming: "WY",
  "district of columbia": "DC",
};

export const STATE_CODES = new Set(Object.values(STATE_NAME_TO_CODE));

export const NMFC_CLASSES = new Set([
  "50",
  "55",
  "60",
  "65",
  "70",
  "77.5",
  "85",
  "92.5",
  "100",
  "110",
  "125",
  "150",
  "175",
  "200",
  "250",
  "300",
  "400",
  "500",
]);

export const WORD_NUMBERS = {
  a: 1,
  an: 1,
  one: 1,
  two: 2,
  three: 3,
  four: 4,
  five: 5,
  six: 6,
  seven: 7,
  eight: 8,
  nine: 9,
  ten: 10,
  eleven: 11,
  twelve: 12,
  thirteen: 13,
  fourteen: 14,
  fifteen: 15,
  sixteen: 16,
  seventeen: 17,
  eighteen: 18,
  nineteen: 19,
  twenty: 20,
  thirty: 30,
  forty: 40,
  fifty: 50,
  sixty: 60,
  seventy: 70,
  eighty: 80,
  ninety: 90,
};

export const WEEKDAYS = {
  sunday: 0,
  monday: 1,
  tuesday: 2,
  wednesday: 3,
  thursday: 4,
  friday: 5,
  saturday: 6,
};

export const MONTHS = {
  january: 0,
  jan: 0,
  february: 1,
  feb: 1,
  march: 2,
  mar: 2,
  april: 3,
  apr: 3,
  may: 4,
  june: 5,
  jun: 5,
  july: 6,
  jul: 6,
  august: 7,
  aug: 7,
  september: 8,
  sept: 8,
  sep: 8,
  october: 9,
  oct: 9,
  november: 10,
  nov: 10,
  december: 11,
  dec: 11,
};

export const ACCESSORIAL_PATTERNS = [
  { re: /lift\s*-?\s*gates?\s+(?:at\s+)?pick/i, ids: ["liftgate_pickup"] },
  { re: /lift\s*-?\s*gates?\s+(?:at\s+)?deliv/i, ids: ["liftgate_delivery"] },
  { re: /lift\s*-?\s*gates?\s+(?:at\s+)?(?:both|each|either)/i, ids: ["liftgate_pickup", "liftgate_delivery"] },
  {
    re: /lift\s*-?\s*gates?.{0,32}\b(?:pick\w*.{0,16}(?:and|&).{0,16}deliv|deliv\w*.{0,16}(?:and|&).{0,16}pick)/i,
    ids: ["liftgate_pickup", "liftgate_delivery"],
  },
  { re: /inside\s+pick/i, ids: ["inside_pickup"] },
  { re: /inside\s+deliv/i, ids: ["inside_delivery"] },
  { re: /inside\s+both/i, ids: ["inside_pickup", "inside_delivery"] },
  { re: /residential\s+pick/i, ids: ["residential_pickup"] },
  { re: /residential\s+deliv/i, ids: ["residential_delivery"] },
  { re: /limited\s+access\s+pick/i, ids: ["limited_access_pickup"] },
  { re: /limited\s+access\s+deliv/i, ids: ["limited_access_delivery"] },
  { re: /appointment/i, ids: ["appointment_delivery"] },
  { re: /notify/i, ids: ["notify_before_delivery"] },
  {
    re: /protect(?:ed|ing)?\s+from\s+freeze|freeze\s+protect(?:ed|ing)?|freeze\b[\s\w]{0,24}\bprotect(?:ed|ing)?|\bprotect(?:ed|ing)?\b[\s\w]{0,24}\bfreeze|\bplease\s+protect(?:ed|ing)?\b/i,
    ids: ["protect_from_freeze"],
  },
  { re: /residential/i, ids: ["residential_pickup", "residential_delivery"] },
  { re: /limited\s+access/i, ids: ["limited_access_pickup", "limited_access_delivery"] },
];

export const NONE_ACCESSORIALS =
  /\b(no(?:ne|pe)?(?:\s+extras?)?|no accessorials|that's all|thats all|nothing else|standard pickup|no lift\s*-?\s*gate)\b/i;
export const STT_NONE_ACCESSORIALS = /^\s*(num|nun|non|none|nope|no)(?:\s+extras?)?\s*[.!]?\s*$/i;

export const VAGUE_MEASURE =
  /\b(standard class|whatever class|any class|usual class|about a few|a few hundred|not sure|don't know|do not know|idk|guess|around there)\b/i;

export const VAGUE_DATE = /\b(asap|soon|whenever|next week sometime|flexible)\b/i;

export const SPEECH_FILLERS = new Set(["um", "uh", "erm", "uhh", "umm", "hmm", "ah", "er"]);

export const PLACE_NOISE = new Set([
  "um",
  "uh",
  "erm",
  "uhh",
  "umm",
  "hmm",
  "ah",
  "er",
  "ship",
  "shipping",
  "shipper",
  "pallet",
  "pallets",
  "crate",
  "crates",
  "box",
  "boxes",
  "drum",
  "drums",
  "skid",
  "skids",
  "freight",
  "load",
  "loads",
  "send",
  "sending",
  "deliver",
  "delivery",
  "delivered",
  "pickup",
  "pick",
  "quote",
  "quoting",
  "like",
  "want",
  "need",
  "kilogram",
  "kilograms",
  "kilo",
  "kilos",
  "kg",
  "gram",
  "grams",
  "pound",
  "pounds",
  "lb",
  "lbs",
  "oranges",
  "orange",
  "peaches",
  "peach",
  "apples",
  "apple",
  "widgets",
  "widget",
  "commodity",
  "of",
  "from",
  "hunter",
  "the",
  "a",
  "an",
  "destination",
  "dest",
  "origin",
  "zip",
  "zipcode",
  "thousand",
  "hundred",
  "actually",
  "sorry",
  "wait",
  "just",
  "maybe",
  "well",
  "yeah",
  "yes",
  "yep",
  "yup",
  "okay",
  "ok",
  "so",
  "then",
  "now",
  "really",
  "right",
]);

export const PLACE_STOP = new Set([
  "to",
  "through",
  "on",
  "for",
  "weighing",
  "weight",
  "class",
  "pickup",
  "pick",
  "pieces",
  "piece",
  "pallets",
  "pallet",
  "pcs",
  "skids",
  "skid",
  "boxes",
  "box",
  "crates",
  "crate",
  "cartons",
  "carton",
  "drums",
  "drum",
  "lb",
  "lbs",
  "pound",
  "pounds",
  "email",
  "commodity",
  "freight",
  "need",
  "want",
  "with",
  "and",
  "tomorrow",
  "today",
  "yesterday",
  "liftgate",
  "residential",
  "inside",
  "appointment",
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
  "sunday",
  "none",
  "hazmat",
  "quote",
  "quoting",
  "please",
  "thanks",
  "ship",
  "shipping",
  "shipper",
  "send",
  "sending",
  "deliver",
  "delivery",
  "load",
  "loads",
  "like",
  "kilogram",
  "kilograms",
  "kg",
  "gram",
  "grams",
  "oranges",
  "orange",
  "peaches",
  "peach",
  "apples",
  "apple",
  "widgets",
  "widget",
  "of",
  "from",
  "hunter",
  "the",
  "a",
  "an",
  "destination",
  "dest",
  "origin",
  "zip",
  "zipcode",
  "is",
  "kilo",
  "kilos",
  "thousand",
  "hundred",
  "actually",
  "sorry",
  "wait",
  "just",
  "maybe",
  "well",
  "yeah",
  "yes",
  "yep",
  "yup",
  "okay",
  "ok",
  "so",
  "then",
  "now",
  "really",
  "right",
]);

export const ZIP_PREFIX_NOISE = new Set([
  "actually",
  "sorry",
  "wait",
  "just",
  "maybe",
  "well",
  "yeah",
  "yes",
  "yep",
  "yup",
  "okay",
  "ok",
  "so",
  "then",
  "now",
  "really",
  "right",
  "hmm",
  "please",
  "thanks",
  "thank",
]);

export const LEADING_FILLER = /^(need|please|want|hi|hello|quote|ship|shipping|can|we|i|get)\b/i;

/** Common US freight cities — used only to split “from Atlanta Austin”, never to invent ZIPs. */
export const US_CITIES = new Set(
  [
    "akron",
    "albuquerque",
    "alexandria",
    "allentown",
    "amarillo",
    "anaheim",
    "anchorage",
    "ann arbor",
    "arlington",
    "atlanta",
    "augusta",
    "aurora",
    "austin",
    "bakersfield",
    "baltimore",
    "baton rouge",
    "boise",
    "boston",
    "buffalo",
    "chandler",
    "charleston",
    "charlotte",
    "chattanooga",
    "chesapeake",
    "chicago",
    "chula vista",
    "cincinnati",
    "cleveland",
    "colorado springs",
    "columbus",
    "corpus christi",
    "dallas",
    "dayton",
    "denver",
    "des moines",
    "detroit",
    "durham",
    "el paso",
    "fort lauderdale",
    "fort wayne",
    "fort worth",
    "fremont",
    "fresno",
    "garland",
    "gilbert",
    "glendale",
    "grand rapids",
    "greensboro",
    "henderson",
    "hialeah",
    "honolulu",
    "houston",
    "huntington beach",
    "indianapolis",
    "irvine",
    "irving",
    "jacksonville",
    "jersey city",
    "kansas city",
    "knoxville",
    "laredo",
    "las vegas",
    "lexington",
    "lincoln",
    "little rock",
    "long beach",
    "los angeles",
    "louisville",
    "lubbock",
    "madison",
    "memphis",
    "mesa",
    "miami",
    "milwaukee",
    "minneapolis",
    "mobile",
    "modesto",
    "montgomery",
    "nashville",
    "new orleans",
    "new york",
    "newark",
    "norfolk",
    "north las vegas",
    "oakland",
    "oklahoma city",
    "omaha",
    "orlando",
    "overland park",
    "oxnard",
    "philadelphia",
    "phoenix",
    "pittsburgh",
    "plano",
    "portland",
    "providence",
    "raleigh",
    "reno",
    "richmond",
    "riverside",
    "rochester",
    "sacramento",
    "saint louis",
    "saint paul",
    "salt lake city",
    "san antonio",
    "san bernardino",
    "san diego",
    "san francisco",
    "san jose",
    "santa ana",
    "santa clarita",
    "scottsdale",
    "seattle",
    "spokane",
    "st louis",
    "st paul",
    "st petersburg",
    "stockton",
    "syracuse",
    "tacoma",
    "tampa",
    "toledo",
    "tucson",
    "tulsa",
    "virginia beach",
    "washington",
    "wichita",
    "winston-salem",
    "worcester",
  ].map((s) => s.toLowerCase()),
);

/** First-3 ZIP prefixes for obvious metro conflicts. Never invents a ZIP. */
export const ZIP_PREFIX_METRO = {
  300: { city: "Atlanta", state: "GA" },
  301: { city: "Atlanta", state: "GA" },
  302: { city: "Atlanta", state: "GA" },
  303: { city: "Atlanta", state: "GA" },
  787: { city: "Austin", state: "TX" },
  786: { city: "Austin", state: "TX" },
  606: { city: "Chicago", state: "IL" },
  607: { city: "Chicago", state: "IL" },
  752: { city: "Dallas", state: "TX" },
  753: { city: "Dallas", state: "TX" },
  750: { city: "Dallas", state: "TX" },
  770: { city: "Houston", state: "TX" },
  772: { city: "Houston", state: "TX" },
  100: { city: "New York", state: "NY" },
  101: { city: "New York", state: "NY" },
  112: { city: "New York", state: "NY" },
  900: { city: "Los Angeles", state: "CA" },
  901: { city: "Los Angeles", state: "CA" },
  941: { city: "San Francisco", state: "CA" },
  850: { city: "Phoenix", state: "AZ" },
  191: { city: "Philadelphia", state: "PA" },
  981: { city: "Seattle", state: "WA" },
  802: { city: "Denver", state: "CO" },
  "021": { city: "Boston", state: "MA" },
  331: { city: "Miami", state: "FL" },
  372: { city: "Nashville", state: "TN" },
  891: { city: "Las Vegas", state: "NV" },
  282: { city: "Charlotte", state: "NC" },
};
